---
abstract: 'cpan repository server'
author:
  - 'Alexey Melezhik / melezhik@gmail.com'
build_requires:
  Module::Build: 0
configure_requires:
  Module::Build: 0.38
dynamic_config: 1
generated_by: 'Module::Build version 0.38, CPAN::Meta::Converter version 2.112150'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: CPAN-Repo
provides:
  CPAN::Repo:
    file: lib/CPAN/Repo.pm
    version: v0.0.2
  CPAN::Repo::Server:
    file: lib/CPAN/Repo/Server.pm
    version: 0
requires:
  Dancer: 0
  Test::More: 0
resources:
  license: http://dev.perl.org/licenses/
version: v0.0.2
